### ISSUE TITLE
Doesn't work with atom-material-ui

### ISSUE THREAD

**Issue by garrettw** [maxgalbu/atom-tab-close-always-visible#1]
I just tried this out with the `atom-material-ui` theme, and it doesn't work at all. In fact, the close button's visibility is unchanged but the active tab's highlight bar disappears. So I had to disable it.

[edit] I decided to fix this on my own, so here's what I had to end up putting in my user stylesheet. This was really all I needed all along.
```css
.tab-bar .tab .close-icon {
  transform: scale(1);
}
```
